73 sections arent being garbage collected
mcdougallab/matlabneuroninterface pull request #85
Opened 2023-11-03 08:25 UTC by edovanveen

2023-11-03 08:42 UTC, AljenU approved these changes

2023-11-17 11:21 UTC, edovanveen commented
@ramcdougal can I merge this one?

2023-11-21 23:40 UTC, ramcdougal requested changes
There's one specific change that's needed to suppress printing. (add curly braces, see comment).

Because of the all_sections test and because sections are now handles, I think this should work, but can you confirm that something like:
```matlab
axon = n.Section("axon");
axon2 = axon;
axon = 42;
axon2.L = 47;
```
still works? That is, as long as there is a way to get to the section, the destructor should not be called.

2023-11-21 23:40 UTC, ramcdougal commented on +neuron/Section.m
> +            clib.neuron.hoc_oc("delete_section()");  % Annoyingly, this outputs '1' to the console.
To suppress printing, add curly braces:

```matlab
 clib.neuron.hoc_oc("{delete_section()}");
```

2023-11-27 12:44 UTC, edovanveen commented
@ramcdougal 

This seems to work okay:

```matlab
>> n = neuron.Neuron();
>> axon = n.Section("axon");
>> axon2 = axon;
>> axon.length = 42;
>> axon.length

ans =

    42

>> axon2.length = 72;
>> axon.length

ans =

    72

>> clear axon;
>> axon2.length

ans =

    72

>> clear axon;
>> n.topology();

|-|       axon(0-1)

>> clear axon2;
>> n.topology();


```

2023-11-27 14:18 UTC, merged